#!/usr/bin/env python3
"""Synchronize Claude and Codex project settings through a neutral JSON file.

The neutral files under ``ai/tool-settings/`` are meant to be readable and
editable by humans. Native files remain editable too: this script imports
entries from both sides, unions them by stable identity, then renders the
native formats back out.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from copy import deepcopy
from pathlib import Path
from typing import Any


TRACKED_SHARED = Path("ai/tool-settings/settings.json")
LOCAL_SHARED = Path("ai/tool-settings/settings.local.json")
CLAUDE_SETTINGS = Path(".claude/settings.json")
CLAUDE_LOCAL = Path(".claude/settings.local.json")
CODEX_HOOKS = Path(".codex/hooks.json")
CODEX_LOCAL_HOOKS = Path(".codex/hooks.local.json")
CODEX_CONFIG = Path.home() / ".codex" / "config.toml"
SHARED_SKILLS = Path("ai/skills")
AGENTS_SKILLS = Path(".agents/skills")
CLAUDE_SKILLS = Path(".claude/skills")
CLAUDE_COMMANDS = Path(".claude/commands")
CODEX_COMMANDS = Path(".codex/commands")
GENERATED_MARKER = "<!-- Generated by scripts/°base/ai/settings/sync.py; do not edit directly. -->"

_FEATURE_ASSIGNMENT = re.compile(
    r"^(\s*)(codex_hooks|hooks)\s*=\s*([^\n#]*?)(\s*(?:#.*)?)(\r?\n)?$"
)
_FRONTMATTER = re.compile(r"\A---\r?\n(.*?)\r?\n---\r?\n(.*)\Z", re.DOTALL)
_META_LINE = re.compile(r"^([A-Za-z0-9_-]+):\s*(.*)$")


def _git_root() -> Path:
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True,
        text=True,
    )
    if result.returncode == 0 and result.stdout.strip():
        return Path(result.stdout.strip())
    return Path.cwd()


def _read_json(path: Path) -> dict[str, Any]:
    if not path.is_file():
        return {}
    with path.open(encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return data


def _write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    path.write_text(text, encoding="utf-8")


def _features_bounds(lines: list[str]) -> tuple[int, int] | None:
    start = None
    for index, line in enumerate(lines):
        stripped = line.strip()
        if not stripped.startswith("[") or not stripped.endswith("]"):
            continue
        if stripped == "[features]":
            start = index + 1
            continue
        if start is not None:
            return start, index
    if start is None:
        return None
    return start, len(lines)


def _rewrite_codex_feature_flag(text: str) -> tuple[str, bool]:
    lines = text.splitlines(keepends=True)
    bounds = _features_bounds(lines)
    if bounds is None:
        return text, False

    start, end = bounds
    hooks_present = False
    deprecated_indexes: list[int] = []
    replacement = None

    for index in range(start, end):
        match = _FEATURE_ASSIGNMENT.match(lines[index])
        if not match:
            continue
        indent, name, value, comment, newline = match.groups()
        if name == "hooks":
            hooks_present = True
        elif name == "codex_hooks":
            deprecated_indexes.append(index)
            if replacement is None:
                replacement = f"{indent}hooks = {value.strip()}{comment}{newline or ''}"

    if not deprecated_indexes:
        return text, False

    rewritten = []
    for index, line in enumerate(lines):
        if index not in deprecated_indexes:
            rewritten.append(line)
            continue
        if hooks_present or index != deprecated_indexes[0]:
            continue
        rewritten.append(replacement or "hooks = true\n")
    return "".join(rewritten), True


def _ask_codex_config_migration(path: Path) -> str:
    while True:
        answer = input(
            "Codex config uses deprecated [features].codex_hooks. "
            "Migrate it to [features].hooks? [y/n/exit] "
        ).strip().lower()
        if answer in {"y", "yes"}:
            return "yes"
        if answer in {"n", "no"}:
            return "no"
        if answer in {"e", "exit", "x"}:
            print(path)
            return "exit"
        print("Please answer y, n, or exit.")


def _migrate_codex_feature_flag(path: Path, apply: bool, interactive: bool) -> int:
    if not path.is_file():
        return 0
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"Could not read Codex config {path}: {exc}", file=sys.stderr)
        return 1

    rewritten, changed = _rewrite_codex_feature_flag(text)
    if not changed:
        return 0
    if not apply:
        print(f"Codex config uses deprecated [features].codex_hooks: {path}")
        return 0
    if not interactive:
        print(
            f"Codex config uses deprecated [features].codex_hooks; "
            f"run this script interactively to migrate it: {path}",
            file=sys.stderr,
        )
        return 0

    answer = _ask_codex_config_migration(path)
    if answer == "no":
        return 0
    if answer == "exit":
        return 1

    try:
        path.write_text(rewritten, encoding="utf-8")
    except OSError as exc:
        print(f"Could not write Codex config {path}: {exc}", file=sys.stderr)
        return 1
    print(f"Migrated Codex config feature flag: {path}")
    return 0


def _hook_id(event: str, entry: dict[str, Any]) -> str:
    matcher = entry.get("matcher") or ""
    commands = []
    for hook in entry.get("hooks") or []:
        if isinstance(hook, dict):
            commands.append(_neutralize_command(hook.get("command") or ""))
    return "\0".join([event, matcher, "\0".join(commands)])


def _matcher_tokens(entry: dict[str, Any]) -> set[str]:
    matcher = str(entry.get("matcher") or "")
    return {part for part in matcher.split("|") if part} or {""}


def _entry_commands(entry: dict[str, Any]) -> set[str]:
    commands: set[str] = set()
    for hook in entry.get("hooks") or []:
        if isinstance(hook, dict):
            commands.add(_neutralize_command(str(hook.get("command") or "")))
    return commands


def _subsumes(a: dict[str, Any], b: dict[str, Any]) -> bool:
    """True when entry ``a`` covers everything entry ``b`` covers."""
    return _matcher_tokens(a).issuperset(_matcher_tokens(b)) and _entry_commands(a).issuperset(_entry_commands(b))


def _overlay_entry(existing: dict[str, Any], incoming: dict[str, Any]) -> dict[str, Any]:
    merged = deepcopy(existing)
    for key, value in incoming.items():
        if key != "hooks":
            merged[key] = deepcopy(value)

    existing_hooks = merged.get("hooks") if isinstance(merged.get("hooks"), list) else []
    incoming_hooks = incoming.get("hooks") if isinstance(incoming.get("hooks"), list) else []
    hooks = []
    for index, hook in enumerate(incoming_hooks):
        if not isinstance(hook, dict):
            continue
        if index < len(existing_hooks) and isinstance(existing_hooks[index], dict):
            merged_hook = deepcopy(existing_hooks[index])
            merged_hook.update(deepcopy(hook))
            hooks.append(merged_hook)
        else:
            hooks.append(deepcopy(hook))
    if hooks:
        merged["hooks"] = hooks
    return merged


def _unique(values: list[Any]) -> list[Any]:
    seen: set[str] = set()
    out: list[Any] = []
    for value in values:
        key = json.dumps(value, sort_keys=True, ensure_ascii=False)
        if key in seen:
            continue
        seen.add(key)
        out.append(value)
    return out


def _normalize_native(data: dict[str, Any]) -> dict[str, Any]:
    hooks = deepcopy(data.get("hooks") or {})
    for entries in hooks.values():
        if not isinstance(entries, list):
            continue
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            for hook in entry.get("hooks") or []:
                if isinstance(hook, dict):
                    hook["command"] = _neutralize_command(str(hook.get("command") or ""))
    return {
        "version": 1,
        "hooks": hooks,
        "permissions": deepcopy(data.get("permissions") or {}),
    }


def _merge(base: dict[str, Any], incoming: dict[str, Any]) -> dict[str, Any]:
    merged = _normalize_native(base)
    incoming = _normalize_native(incoming)

    hooks = deepcopy(merged.get("hooks") or {})
    for event, entries in (incoming.get("hooks") or {}).items():
        if not isinstance(entries, list):
            continue
        current = [deepcopy(entry) for entry in hooks.get(event, []) if isinstance(entry, dict)]
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            entry_id = _hook_id(event, entry)
            replaced = False
            for index, existing in enumerate(current):
                if _hook_id(event, existing) == entry_id:
                    current[index] = _overlay_entry(existing, entry)
                    replaced = True
                    break
            if replaced:
                continue
            if any(_subsumes(existing, entry) for existing in current):
                continue
            current = [existing for existing in current if not _subsumes(entry, existing)]
            by_id = {_hook_id(event, existing): existing for existing in current}
            by_id[entry_id] = deepcopy(entry)
            current = list(by_id.values())
        hooks[event] = current
    merged["hooks"] = hooks

    permissions = deepcopy(merged.get("permissions") or {})
    incoming_permissions = incoming.get("permissions") or {}
    for key in ("allow", "deny"):
        values = list(permissions.get(key) or [])
        values.extend(incoming_permissions.get(key) or [])
        permissions[key] = _unique(values)
    merged["permissions"] = permissions
    return merged


def _replace_tool_arg(command: str, tool: str) -> str:
    if (
        "save-prompt/hook.py" in command
        or "save-decision/hook.py" in command
        or "save-plan/hook.py" in command
    ):
        command = command.replace("'claude'", f"'{tool}'")
        command = command.replace('"claude"', f'"{tool}"')
        if "save-plan/hook.py" in command and not re.search(r"['\"](?:claude|codex)['\"]", command):
            command = f"{command} '{tool}'"
    return command


def _normalize_command_path(command: str) -> str:
    command = command.replace("python3 .claude/hooks/permission-check.py", 'python3 "$(git rev-parse --show-toplevel)/.claude/hooks/permission-check.py"')
    return command


def _neutralize_command(command: str) -> str:
    command = _normalize_command_path(command)
    if (
        "save-prompt/hook.py" in command
        or "save-decision/hook.py" in command
        or "save-plan/hook.py" in command
    ):
        command = command.replace("'codex'", "'claude'")
        command = command.replace('"codex"', '"claude"')
        if "save-plan/hook.py" in command and not re.search(r"['\"](?:claude|codex)['\"]", command):
            command = f"{command} 'claude'"
    return command


def _render_hooks(shared: dict[str, Any], tool: str) -> dict[str, Any]:
    rendered: dict[str, Any] = {"hooks": {}}
    for event, entries in (shared.get("hooks") or {}).items():
        if not isinstance(entries, list):
            continue
        rendered_entries = []
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            new_entry = deepcopy(entry)
            hooks = []
            for hook in new_entry.get("hooks") or []:
                if not isinstance(hook, dict):
                    continue
                new_hook = deepcopy(hook)
                command = str(new_hook.get("command") or "")
                command = _normalize_command_path(_replace_tool_arg(command, tool))
                new_hook["command"] = command
                if tool == "codex":
                    new_hook.pop("async", None)
                hooks.append(new_hook)
            new_entry["hooks"] = hooks
            rendered_entries.append(new_entry)
        if rendered_entries:
            rendered["hooks"][event] = rendered_entries
    return rendered


def render_claude(shared: dict[str, Any]) -> dict[str, Any]:
    data = _render_hooks(shared, "claude")
    permissions = shared.get("permissions")
    if permissions:
        data["permissions"] = deepcopy(permissions)
    return data


def render_codex_hooks(shared: dict[str, Any]) -> dict[str, Any]:
    return _render_hooks(shared, "codex")


def _same_json(path: Path, data: dict[str, Any]) -> bool:
    if not path.is_file():
        return False
    return _read_json(path) == data


def _parse_markdown_frontmatter(text: str) -> tuple[dict[str, str], str] | None:
    match = _FRONTMATTER.match(text)
    if not match:
        return None
    metadata: dict[str, str] = {}
    for line in match.group(1).splitlines():
        line_match = _META_LINE.match(line)
        if not line_match:
            continue
        key, value = line_match.groups()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] == '"':
            value = json.loads(value)
        elif len(value) >= 2 and value[0] == value[-1] == "'":
            value = value[1:-1]
        metadata[key] = value
    return metadata, match.group(2)


def _yaml_scalar(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _is_generated_markdown(text: str) -> bool:
    return GENERATED_MARKER in text[:1000]


def _skill_name_from_path(path: Path) -> str:
    if path.name == "SKILL.md":
        return path.parent.name
    return path.stem


def _skill_slug(name: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9_.-]+", "-", name).strip("-")
    return slug or "skill"


def _read_skill_source(path: Path, skip_generated: bool = True) -> dict[str, Any] | None:
    if not path.is_file():
        return None
    text = path.read_text(encoding="utf-8")
    if skip_generated and _is_generated_markdown(text):
        return None
    parsed = _parse_markdown_frontmatter(text)
    metadata = parsed[0] if parsed else {}
    body = parsed[1] if parsed else text
    name = metadata.get("name") or _skill_name_from_path(path)
    description = metadata.get("description") or ""
    return {
        "name": name,
        "description": description,
        "body": body,
        "text": text,
        "mtime": path.stat().st_mtime,
        "path": path,
    }


def _iter_skill_source_paths() -> list[tuple[Path, str]]:
    paths: list[tuple[Path, str]] = []
    if SHARED_SKILLS.is_dir():
        paths.extend((path, "shared") for path in sorted(SHARED_SKILLS.glob("*/SKILL.md")))
    if AGENTS_SKILLS.is_dir():
        paths.extend((path, "codex_skill") for path in sorted(AGENTS_SKILLS.glob("*/SKILL.md")))
    if CLAUDE_SKILLS.is_dir():
        paths.extend((path, "claude_skill") for path in sorted(CLAUDE_SKILLS.glob("*/SKILL.md")))
    if CLAUDE_COMMANDS.is_dir():
        paths.extend((path, "claude_command") for path in sorted(CLAUDE_COMMANDS.glob("*.md")))
    if CODEX_COMMANDS.is_dir():
        paths.extend((path, "codex_command") for path in sorted(CODEX_COMMANDS.glob("*.md")))
    return paths


def _collect_skill_sources() -> tuple[dict[str, dict[str, Any]], dict[str, set[Path]]]:
    selected: dict[str, dict[str, Any]] = {}
    claude_paths: dict[str, set[Path]] = {}

    for path, kind in _iter_skill_source_paths():
        source = _read_skill_source(path)
        if source is None:
            continue
        name = str(source["name"])
        if kind.startswith("claude_"):
            claude_paths.setdefault(name, set()).add(path)
        current = selected.get(name)
        if current is None or float(source["mtime"]) >= float(current["mtime"]):
            selected[name] = source

    return selected, claude_paths


def _render_canonical_skill(name: str, description: str, body: str) -> str:
    body = body.lstrip("\n")
    return (
        f"---\n"
        f"name: {_yaml_scalar(name)}\n"
        f"description: {_yaml_scalar(description)}\n"
        f"---\n\n"
        f"{body}"
    )


def _render_claude_skill_wrapper(name: str, description: str, shared_path: Path) -> str:
    return (
        f"---\n"
        f"name: {_yaml_scalar(name)}\n"
        f"description: {_yaml_scalar(description)}\n"
        f"---\n\n"
        f"{GENERATED_MARKER}\n\n"
        f"# {name}\n\n"
        f"Read and follow the canonical skill at `{shared_path.as_posix()}` before acting.\n"
        f"When updating this skill, edit the canonical source and run the AI settings sync.\n"
    )


def _render_codex_skill_wrapper(name: str, description: str, shared_path: Path) -> str:
    return (
        f"---\n"
        f"name: {_yaml_scalar(name)}\n"
        f"description: {_yaml_scalar(description)}\n"
        f"---\n\n"
        f"{GENERATED_MARKER}\n\n"
        f"# {name}\n\n"
        f"Read and follow the canonical skill at `{shared_path.as_posix()}` before acting.\n"
        f"When updating this skill, edit the canonical source and run the AI settings sync.\n"
    )


def _render_claude_command_shim(name: str, description: str, shared_path: Path) -> str:
    command_description = description or f"Invoke the {name} skill."
    return (
        f"---\n"
        f"name: {_yaml_scalar(name)}\n"
        f"description: {_yaml_scalar(command_description)}\n"
        f"---\n\n"
        f"{GENERATED_MARKER}\n\n"
        f"Use the `{name}` skill for this request. The canonical source is "
        f"`{shared_path.as_posix()}`.\n"
    )


def _write_text_if_changed(path: Path, text: str, apply: bool) -> list[str]:
    if path.is_file() and path.read_text(encoding="utf-8") == text:
        return []
    if apply:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return [str(path)]


def _sync_skills(apply: bool) -> list[str]:
    changed: list[str] = []
    sources, claude_paths = _collect_skill_sources()
    if not sources:
        return changed

    for name, source in sorted(sources.items()):
        slug = _skill_slug(name)
        shared_path = SHARED_SKILLS / slug / "SKILL.md"
        description = str(source["description"])
        skill_text = _render_canonical_skill(name, description, str(source["body"]))
        changed.extend(_write_text_if_changed(shared_path, skill_text, apply))

        codex_skill_path = AGENTS_SKILLS / slug / "SKILL.md"
        claude_skill_paths = {CLAUDE_SKILLS / slug / "SKILL.md"}
        claude_command_paths = {CLAUDE_COMMANDS / f"{slug}.md"}
        for path in claude_paths.get(name, set()):
            if path.name == "SKILL.md":
                claude_skill_paths.add(path)
            elif path.suffix == ".md":
                claude_command_paths.add(path)

        codex_wrapper = _render_codex_skill_wrapper(name, description, shared_path)
        skill_wrapper = _render_claude_skill_wrapper(name, description, shared_path)
        command_shim = _render_claude_command_shim(name, description, shared_path)
        changed.extend(_write_text_if_changed(codex_skill_path, codex_wrapper, apply))
        for path in sorted(claude_skill_paths):
            changed.extend(_write_text_if_changed(path, skill_wrapper, apply))
        for path in sorted(claude_command_paths):
            changed.extend(_write_text_if_changed(path, command_shim, apply))

    return changed


def _load_layer(shared_path: Path, claude_path: Path, codex_path: Path) -> dict[str, Any]:
    shared = _read_json(shared_path)
    if shared:
        shared = _merge({}, shared)
    native_sources: list[tuple[float, dict[str, Any]]] = []
    for path in (claude_path, codex_path):
        if path.is_file():
            native_sources.append((path.stat().st_mtime, _read_json(path)))
    if not shared and native_sources:
        shared = _normalize_native(sorted(native_sources, key=lambda item: item[0])[-1][1])
    for _, data in sorted(native_sources, key=lambda item: item[0]):
        shared = _merge(shared, data)
    return shared or {"version": 1, "hooks": {}, "permissions": {"allow": [], "deny": []}}


def _apply_or_check(shared_path: Path, claude_path: Path, codex_path: Path, apply: bool) -> list[str]:
    changed: list[str] = []
    shared = _load_layer(shared_path, claude_path, codex_path)
    claude = render_claude(shared)
    codex = render_codex_hooks(shared)

    for path, data in (
        (shared_path, shared),
        (claude_path, claude),
        (codex_path, codex),
    ):
        if _same_json(path, data):
            continue
        changed.append(str(path))
        if apply:
            _write_json(path, data)

    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--apply", action="store_true", help="write synchronized files")
    parser.add_argument("--check", action="store_true", help="fail if files are out of sync")
    parser.add_argument("--explain", action="store_true", help="print changed paths")
    args = parser.parse_args(argv)

    os.chdir(_git_root())
    apply = args.apply and not args.check
    config_status = 0
    if apply or args.check:
        config_status = _migrate_codex_feature_flag(CODEX_CONFIG, apply, sys.stdin.isatty())

    changed = []
    changed.extend(_apply_or_check(TRACKED_SHARED, CLAUDE_SETTINGS, CODEX_HOOKS, apply))
    if LOCAL_SHARED.is_file() or CLAUDE_LOCAL.is_file() or CODEX_LOCAL_HOOKS.is_file():
        changed.extend(_apply_or_check(LOCAL_SHARED, CLAUDE_LOCAL, CODEX_LOCAL_HOOKS, apply))
    changed.extend(_sync_skills(apply))

    if changed and (args.explain or args.check):
        print("AI tool settings are out of sync:")
        for path in changed:
            print(f"  {path}")
    if args.check and changed:
        return 1
    if config_status:
        return config_status
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
